# Directory containing the impacts results tree
results-root: /shares/gcp/outputs/covariates/results-wilson

# Calculate values over the Monte Carlo results?
do-montecarlo: no

yearsets: [[1980, 1999], [2000, 2019], [2020, 2039], [2040, 2059], [2060, 2079], [2080, 2099]]
regions: [global, countries, funds]

# Format for the output
output-format: edfcsv
evalqvals: ['mean', 'sdev']