# Directory containing the impacts results tree
results-root: /shares/gcp/outputs/covariates/results-michener
# Directory to write output files
output-dir: covariates

# Calculate values over the Monte Carlo results?
do-montecarlo: no

# Which column to read from the files (the final result is 'rebased')
column: tas

yearsets: [[1980, 1999], [2000, 2019], [2020, 2039], [2040, 2059], [2060, 2079], [2080, 2099]]
regions: [global, countries]
suffix: -{column}

# Format for the output
output-format: valuescsv