# Directory containing the impacts results tree
results-root: /shares/gcp/outputs/nasmort
# Directory to write output quantile files
output-dir: quantiles

# Calculate values over the Monte Carlo results?
do-montecarlo: yes
# Collect results into sets of years?
do-yearsets: yes
# Report the mean of these sets of years?
do-yearsetmeans: yes
# In constructing empirical distribution function, use GCP-specific weights?
do-gcmweights: yes

# Perform operations for only one RCP or realization?
only-rcp: null # e.g., rcp85
# Which impacts should be included?  List or all
only-impacts: all
# Which GCM models should we include?  List or all
only-models: all

# Which column to read from the files (the final result is 'debased')
column: debased
