# Directory containing the impacts results tree
results-root: /shares/gcp/outputs/labor/impacts-andrena
# Directory to write output files
output-dir: results

# Calculate values over the Monte Carlo results?
do-montecarlo: no

# Perform operations for only one RCP or realization?
only-rcp: null # e.g., rcp85
# Which GCM models should we include?  List or all
only-models: all
# What file(s) should be required
checks: COMPLETE

# Which column to read from the files (the final result is 'rebased')
column: rebased

# Format for the output
output-format: edfcsv