# Directory containing the impacts results tree
results-root: /shares/gcp/outputs/nasmort-fireant
# Directory to write output files
output-dir: /shares/gcp/outputs/timeseries-fireant

# Calculate values over the Monte Carlo results?
do-montecarlo: yes

# Perform operations for only one RCP or realization?
only-rcp: null # e.g., rcp85
# Which GCM models should we include?  List or all
only-models: all

# Which column to read from the files (the final result is 'debased')
column: debased
